In [1]:
import numpy as np

In [2]:
mlst = [1,2,3]

In [3]:
mlst

[1, 2, 3]

In [4]:
marr = np.array(mlst)

In [5]:
marr

array([1, 2, 3])

In [6]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [9]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [11]:
np.random.seed(101)
arr = np.random.randint(0, 100, 10)

In [12]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [13]:
arr2 = np.random.randint(0, 100, 10)

In [14]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [15]:
arr.max()

95

In [16]:
arr.argmax() # index position of max value

0

In [17]:
arr.mean()

60.8

In [18]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [19]:
arr.reshape((5,2))

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [20]:
arr.reshape((10, 1))

array([[95],
       [11],
       [81],
       [70],
       [63],
       [87],
       [75],
       [ 9],
       [77],
       [40]])

In [21]:
mat = np.arange(0, 100).reshape((10, 10))

In [22]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [23]:
# Indexing
r = 0 # Row
c = 1 # Column
mat[r, c] # Element at 0 row and 1 column

1

In [24]:
mat[5, 8]

58

In [25]:
# Sclicing
mat[:, 1] 

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [26]:
mat[1, :]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])